export const currencyList = {
    CAD: 'Canadian dollar',
    HKD: 'Honk Kong dollar',
    ISK: 'Icelandic króna',
    PHP: 'Philippine peso',
    DKK: 'Danish krone',
    HUF: 'Hungarian forint',
    CZK: 'Czech koruna',
    GBP: 'Pound sterling',
    RON: 'Romanian leu',
    SEK: 'Swedish krona',
    IDR: 'Indonesian rupiah',
    INR: 'Indian rupee',
    BRL: 'Brazilian real',
    RUB: 'Russian ruble',
    HRK: 'Croatian kuna',
    JPY: 'Japanese yen',
    THB: 'Thai baht',
    CHF: 'Swiss franc',
    EUR: 'Euro',
    MYR: 'Malaysian ringgit',
    BGN: 'Bulgarian lev',
    TRY: 'Turkish lira',
    CNY: 'Renminbi',
    NOK: 'Norwegian krone',
    NZD: 'New Zealand dollar',
    ZAR: 'South African rand',
    USD: 'United States dollar',
    MXN: 'Mexican peso',
    SGD: 'Singapore dollar',
    AUD: 'Australian dollar',
    ILS: 'Israeli new shekel',
    KRW: 'South Korean won',
    PLN: 'Polish złoty',
}